sudo: false
language: python
python:
  - "3.4"
install:
  - pyvenv .
  - bin/pip install flake8
script:
  - bin/flake8 apps policycompass_services --ignore E501,F403 --exclude migrations
after_success:
  - "[[ $TRAVIS_BRANCH = master && $TRAVIS_PULL_REQUEST = false ]] && openssl aes-256-cbc -K $encrypted_c94ec13a7483_key -iv $encrypted_c94ec13a7483_iv -in travis_deploy_key.enc -out travis_deploy_key -d"
  - "[[ $TRAVIS_BRANCH = master && $TRAVIS_PULL_REQUEST = false ]] && ssh -p 5555 -oStrictHostKeyChecking=no -i travis_deploy_key policycompass@stage.policycompass.eu"
